packages:
  - apps/*
  - libs/*
  - tools/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - lmdb
  - msgpackr-extract
  - nx
  - unrs-resolver

overrides:
  on-headers@<1.1.0: '>=1.1.0'
  qs@<6.14.1: '>=6.14.1'
  vite@>=6.0.0 <=6.3.5: '>=6.3.6'
  vite@>=6.0.0 <=6.4.0: '>=6.4.1'
