packages:
  - apps/*
  - libs/*
  - tools/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - lmdb
  - msgpackr-extract
  - nx
  - oxc-resolver
  - unrs-resolver

overrides:
  '@modelcontextprotocol/sdk@<1.25.2': '>=1.25.2'
  diff@<8.0.3: '>=8.0.3'
  hono@<4.11.4: '>=4.11.4'
  on-headers@<1.1.0: '>=1.1.0'
  qs@<6.14.1: '>=6.14.1'
  tar@<=7.5.2: '>=7.5.3'
  undici@>=7.0.0 <7.18.2: '>=7.18.2'
  vite@>=6.0.0 <=6.3.5: '>=6.3.6'
  vite@>=6.0.0 <=6.4.0: '>=6.4.1'
