packages:
  - apps/*
  - libs/*
  - tools/*

allowBuilds:
  esbuild: set this to true or false
  lmdb: set this to true or false

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - lmdb
  - msgpackr-extract
  - nx
  - oxc-resolver
  - unrs-resolver
