@Api_HostAddress = https://localhost:60254/api
@access_token = <paste_access_token_here>
@email = <your_email>
@password = <your_password>

### Register
POST {{Api_HostAddress}}/account/register
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###

### Login and retrieve tokens
POST {{Api_HostAddress}}/account/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###

GET {{Api_HostAddress}}/weatherforecastsplus
Accept: application/json
Authorization: Bearer {{access_token}}

###
